apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoever-platform
  namespace: app
  labels:
    app: autoever-web
spec:
  replicas: 2 # 가용성을 위해 2개
  selector:
    matchLabels:
      app: autoever-web
  template:
    metadata:
      labels:
        app: autoever-web
    spec:
      serviceAccountName: platform-viewer
      containers:
      - name: platform
        image: 471112567060.dkr.ecr.ap-northeast-2.amazonaws.com/autoever-guestbook:0b44a5acc8da25a2d2951d1a37988b3a9bce9a2a
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # 헬스체크 경로 추가
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10 # 앱 실행 후 10초 뒤부터 체크 시작
          periodSeconds: 15       # 15초마다 한 번씩 찔러보기
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5  # 앱 실행 후 5초 뒤부터 체크 시작
          periodSeconds: 10
        env: # RDS 접속 정보
        - name: DB_HOST
          value: "autoever-db.c1em2swskomv.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASS
          value: "qazwsx64"
        - name: DB_NAME
          value: "guestbook"
        resources:
          requests:
            cpu: "200m"    # 실제 평균 사용량 기준으로 설정
            memory: "280Mi"
